apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: intelliops
  source:
    repoURL: https://github.com/mrsrujan/IntelliOps
    targetRevision: main
    path: helm/security/external-secrets
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: external-secrets.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::ACCOUNT_ID_PLACEHOLDER:role/intelliops-dev-external-secrets"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
