apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
  annotations:
    policies.kyverno.io/title: Require non-root user
    policies.kyverno.io/category: Pod Security
spec:
  validationFailureAction: {{ .Values.validationFailureAction }}
  background: true
  rules:
    - name: run-as-non-root
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [apps-dev]
      validate:
        message: "Containers must set runAsNonRoot: true."
        anyPattern:
          - spec:
              securityContext:
                runAsNonRoot: true
          - spec:
              containers:
                - securityContext:
                    runAsNonRoot: true
